'use strict';

function run(fn) {
    return fn();
}
function blank_object() {
    return Object.create(null);
}
function run_all(fns) {
    fns.forEach(run);
}

let current_component;
function set_current_component(component) {
    current_component = component;
}
function get_current_component() {
    if (!current_component)
        throw new Error(`Function called outside component initialization`);
    return current_component;
}
function onMount(fn) {
    get_current_component().$$.on_mount.push(fn);
}
const escaped = {
    '"': '&quot;',
    "'": '&#39;',
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;'
};
function escape(html) {
    return String(html).replace(/["'&<>]/g, match => escaped[match]);
}
function each(items, fn) {
    let str = '';
    for (let i = 0; i < items.length; i += 1) {
        str += fn(items[i], i);
    }
    return str;
}
let on_destroy;
function create_ssr_component(fn) {
    function $$render(result, props, bindings, slots) {
        const parent_component = current_component;
        const $$ = {
            on_destroy,
            context: new Map(parent_component ? parent_component.$$.context : []),
            // these will be immediately discarded
            on_mount: [],
            before_update: [],
            after_update: [],
            callbacks: blank_object()
        };
        set_current_component({ $$ });
        const html = fn(result, props, bindings, slots);
        set_current_component(parent_component);
        return html;
    }
    return {
        render: (props = {}, options = {}) => {
            on_destroy = [];
            const result = { title: '', head: '', css: new Set() };
            const html = $$render(result, props, {}, options);
            run_all(on_destroy);
            return {
                html,
                css: {
                    code: Array.from(result.css).map(css => css.code).join('\n'),
                    map: null // TODO
                },
                head: result.title + result.head
            };
        },
        $$render
    };
}

/* client/components/Fruits.svelte generated by Svelte v3.20.1 */

const css = {
	code: "h1.svelte-4lobfq{font-family:sans-serif;color:tomato}",
	map: "{\"version\":3,\"file\":\"Fruits.svelte\",\"sources\":[\"Fruits.svelte\"],\"sourcesContent\":[\"<script>\\n\\timport {onMount} from 'svelte';\\n\\texport let fruits;\\n\\n\\tonMount(() => {\\n\\t\\tconsole.log('mounted!');\\n\\t});\\n</script>\\n\\n<h1>Hello Svelte SSR!</h1>\\n\\n<ul>\\n\\t{#each fruits as fruit}\\n\\t\\t<li>{fruit.name}</li>\\n\\t{/each}\\n</ul>\\n\\n<style>\\n\\th1 {\\n\\t\\tfont-family: sans-serif;\\n\\t\\tcolor: tomato;\\n\\t}\\n</style>\"],\"names\":[],\"mappings\":\"AAkBC,EAAE,cAAC,CAAC,AACH,WAAW,CAAE,UAAU,CACvB,KAAK,CAAE,MAAM,AACd,CAAC\"}"
};

const Fruits = create_ssr_component(($$result, $$props, $$bindings, $$slots) => {
	let { fruits } = $$props;

	onMount(() => {
		console.log("mounted!");
	});

	if ($$props.fruits === void 0 && $$bindings.fruits && fruits !== void 0) $$bindings.fruits(fruits);
	$$result.css.add(css);

	return `<h1 class="${"svelte-4lobfq"}">Hello Svelte SSR!</h1>

<ul>${each(fruits, fruit => `<li>${escape(fruit.name)}</li>`)}
</ul>`;
});

module.exports = Fruits;
