'use strict';

function run(fn) {
    return fn();
}
function blank_object() {
    return Object.create(null);
}
function run_all(fns) {
    fns.forEach(run);
}

let current_component;
function set_current_component(component) {
    current_component = component;
}
const escaped = {
    '"': '&quot;',
    "'": '&#39;',
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;'
};
function escape(html) {
    return String(html).replace(/["'&<>]/g, match => escaped[match]);
}
function each(items, fn) {
    let str = '';
    for (let i = 0; i < items.length; i += 1) {
        str += fn(items[i], i);
    }
    return str;
}
function validate_component(component, name) {
    if (!component || !component.$$render) {
        if (name === 'svelte:component')
            name += ' this={...}';
        throw new Error(`<${name}> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules`);
    }
    return component;
}
let on_destroy;
function create_ssr_component(fn) {
    function $$render(result, props, bindings, slots) {
        const parent_component = current_component;
        const $$ = {
            on_destroy,
            context: new Map(parent_component ? parent_component.$$.context : []),
            // these will be immediately discarded
            on_mount: [],
            before_update: [],
            after_update: [],
            callbacks: blank_object()
        };
        set_current_component({ $$ });
        const html = fn(result, props, bindings, slots);
        set_current_component(parent_component);
        return html;
    }
    return {
        render: (props = {}, options = {}) => {
            on_destroy = [];
            const result = { title: '', head: '', css: new Set() };
            const html = $$render(result, props, {}, options);
            run_all(on_destroy);
            return {
                html,
                css: {
                    code: Array.from(result.css).map(css => css.code).join('\n'),
                    map: null // TODO
                },
                head: result.title + result.head
            };
        },
        $$render
    };
}

/* components/Menu.svelte generated by Svelte v3.20.1 */

const css = {
	code: ".Menu.svelte-h6nama.svelte-h6nama{display:flex}.Menu.svelte-h6nama a.svelte-h6nama{margin-right:1rem}",
	map: "{\"version\":3,\"file\":\"Menu.svelte\",\"sources\":[\"Menu.svelte\"],\"sourcesContent\":[\"<div class=\\\"Menu\\\">\\n\\t<a href=\\\"/\\\">Home</a>\\n\\t<a href=\\\"/fruits\\\">Fruits</a>\\n</div>\\n\\n<style lang=\\\"scss\\\">.Menu {\\n  display: flex; }\\n  .Menu a {\\n    margin-right: 1rem; }\\n/*# sourceMappingURL=components/Menu.svelte.map */</style>\"],\"names\":[],\"mappings\":\"AAKmB,KAAK,4BAAC,CAAC,AACxB,OAAO,CAAE,IAAI,AAAE,CAAC,AAChB,mBAAK,CAAC,CAAC,cAAC,CAAC,AACP,YAAY,CAAE,IAAI,AAAE,CAAC\"}"
};

const Menu = create_ssr_component(($$result, $$props, $$bindings, $$slots) => {
	$$result.css.add(css);

	return `<div class="${"Menu svelte-h6nama"}"><a href="${"/"}" class="${"svelte-h6nama"}">Home</a>
	<a href="${"/fruits"}" class="${"svelte-h6nama"}">Fruits</a>
</div>`;
});

/* components/pages/Fruits.svelte generated by Svelte v3.20.1 */

const css$1 = {
	code: "h1.svelte-o0h02v{margin:2rem 0}",
	map: "{\"version\":3,\"file\":\"Fruits.svelte\",\"sources\":[\"Fruits.svelte\"],\"sourcesContent\":[\"<script>\\n\\timport Menu from '../Menu.svelte';\\n\\texport let fruits;\\n</script>\\n\\n<Menu/>\\n\\n<h1>Fruits</h1>\\n\\n<ul>\\n\\t{#each fruits as fruit}\\n\\t\\t<li>{fruit.name}</li>\\n\\t{/each}\\n</ul>\\n\\n<style>\\nh1 {\\n\\tmargin: 2rem 0;\\n}\\n\\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbImNvbXBvbmVudHMvcGFnZXMvRnJ1aXRzLnN2ZWx0ZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQ0E7Q0FDQyxjQUFjO0FBQ2YiLCJmaWxlIjoiY29tcG9uZW50cy9wYWdlcy9GcnVpdHMuc3ZlbHRlIiwic291cmNlc0NvbnRlbnQiOlsiXG5oMSB7XG5cdG1hcmdpbjogMnJlbSAwO1xufVxuIl19 */</style>\"],\"names\":[],\"mappings\":\"AAgBA,EAAE,cAAC,CAAC,AACH,MAAM,CAAE,IAAI,CAAC,CAAC,AACf,CAAC\"}"
};

const Fruits = create_ssr_component(($$result, $$props, $$bindings, $$slots) => {
	let { fruits } = $$props;
	if ($$props.fruits === void 0 && $$bindings.fruits && fruits !== void 0) $$bindings.fruits(fruits);
	$$result.css.add(css$1);

	return `${validate_component(Menu, "Menu").$$render($$result, {}, {}, {})}

<h1 class="${"svelte-o0h02v"}">Fruits</h1>

<ul>${each(fruits, fruit => `<li>${escape(fruit.name)}</li>`)}
</ul>`;
});

module.exports = Fruits;
