'use strict';

var Menu = require('./Menu-7c514057.js');

/* components/pages/Fruits.svelte generated by Svelte v3.20.1 */

const css = {
	code: "h1.svelte-o0h02v{margin:2rem 0}",
	map: "{\"version\":3,\"file\":\"Fruits.svelte\",\"sources\":[\"Fruits.svelte\"],\"sourcesContent\":[\"<script>\\n\\timport Menu from '../Menu.svelte';\\n\\texport let fruits;\\n</script>\\n\\n<Menu/>\\n\\n<h1>Fruits</h1>\\n\\n<ul>\\n\\t{#each fruits as fruit}\\n\\t\\t<li>{fruit.name}</li>\\n\\t{/each}\\n</ul>\\n\\n<style>\\nh1 {\\n\\tmargin: 2rem 0;\\n}\\n\\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbImNvbXBvbmVudHMvcGFnZXMvRnJ1aXRzLnN2ZWx0ZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQ0E7Q0FDQyxjQUFjO0FBQ2YiLCJmaWxlIjoiY29tcG9uZW50cy9wYWdlcy9GcnVpdHMuc3ZlbHRlIiwic291cmNlc0NvbnRlbnQiOlsiXG5oMSB7XG5cdG1hcmdpbjogMnJlbSAwO1xufVxuIl19 */</style>\"],\"names\":[],\"mappings\":\"AAgBA,EAAE,cAAC,CAAC,AACH,MAAM,CAAE,IAAI,CAAC,CAAC,AACf,CAAC\"}"
};

const Fruits = Menu.create_ssr_component(($$result, $$props, $$bindings, $$slots) => {
	let { fruits } = $$props;
	if ($$props.fruits === void 0 && $$bindings.fruits && fruits !== void 0) $$bindings.fruits(fruits);
	$$result.css.add(css);

	return `${Menu.validate_component(Menu.Menu, "Menu").$$render($$result, {}, {}, {})}

<h1 class="${"svelte-o0h02v"}">Fruits</h1>

<ul>${Menu.each(fruits, fruit => `<li>${Menu.escape(fruit.name)}</li>`)}
</ul>`;
});

module.exports = Fruits;
