'use strict';

var index = require('./index-f0425e65.js');

/* components/pages/Test.svelte generated by Svelte v3.20.1 */

const Test = index.create_ssr_component(($$result, $$props, $$bindings, $$slots) => {
	return ``;
});

module.exports = Test;
